spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: orderService
              uri: lb:http://ORDERSERVCICE
              predicates:
                - Path=/api/v1/orders/**
            - id: productService
              uri: lb:http://PRODUCTSERVICE
              predicates:
                - Path=/api/v1/products/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
server:
  port: 8080